# ------------------------------------------------------------------------------


- name: Install
  ansible.builtin.package:
    name: keychain
    state: present
  become: true

- name: Create ~/.local/share/keychain
  ansible.builtin.file:
    state: directory
    path: ~/.local/share/keychain


# ------------------------------------------------------------------------------
# Zsh


- name: "zsh : Add init block to {{ zsh_zprofile_bottom }}"
  ansible.builtin.blockinfile:
    path: "{{ zsh_zprofile_bottom }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      eval `keychain --agents ssh,gpg --timeout 43200 --dir ~/.local/share/keychain --stop others --inherit any --eval id_ed25519 ACCB8F306184BEEE49E7370E5DBF2C327E72AA3F`
  register: task

- name: "zsh : Compile {{ zsh_zprofile_bottom }}"
  when: task.changed
  ansible.builtin.command: zsh -c 'zcompile -R {{ zsh_zprofile_bottom }}'


# ------------------------------------------------------------------------------
# Bash

- name: "bash : Add init block to {{ bash_profile_bottom }}"
  ansible.builtin.blockinfile:
    path: "{{ bash_profile_bottom }}"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      eval `keychain --agents ssh,gpg --timeout 43200 --dir ~/.local/share/keychain --stop others --inherit any --eval id_ed25519 ACCB8F306184BEEE49E7370E5DBF2C327E72AA3F`


# ------------------------------------------------------------------------------
